// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bad4.Data;

#nullable disable

namespace bad4.Migrations
{
    [DbContext(typeof(BakeryDbContext))]
    partial class BakeryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("bad4.Models.Allergen", b =>
                {
                    b.Property<int>("AllergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergenID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.HasKey("AllergenID");

                    b.HasIndex("StockID")
                        .IsUnique();

                    b.ToTable("Allergen");

                    b.HasData(
                        new
                        {
                            AllergenID = 1,
                            Name = "Leavening agent",
                            StockID = 1
                        },
                        new
                        {
                            AllergenID = 2,
                            Name = "Alcohol Free",
                            StockID = 2
                        },
                        new
                        {
                            AllergenID = 3,
                            Name = "Gluten",
                            StockID = 3
                        },
                        new
                        {
                            AllergenID = 4,
                            Name = "Lactose",
                            StockID = 4
                        },
                        new
                        {
                            AllergenID = 5,
                            Name = "Gluten",
                            StockID = 5
                        },
                        new
                        {
                            AllergenID = 6,
                            Name = "Glucose",
                            StockID = 6
                        },
                        new
                        {
                            AllergenID = 7,
                            Name = "Sodium",
                            StockID = 7
                        },
                        new
                        {
                            AllergenID = 8,
                            Name = "Water",
                            StockID = 8
                        },
                        new
                        {
                            AllergenID = 9,
                            Name = "Protein",
                            StockID = 9
                        });
                });

            modelBuilder.Entity("bad4.Models.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("bad4.Models.BakingGoods", b =>
                {
                    b.Property<int>("BakingGoodsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BakingGoodsID"));

                    b.Property<int>("CompanyOrdersID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.HasKey("BakingGoodsID");

                    b.HasIndex("CompanyOrdersID");

                    b.HasIndex("RecipeID")
                        .IsUnique();

                    b.ToTable("BakingGoods");

                    b.HasData(
                        new
                        {
                            BakingGoodsID = 1,
                            CompanyOrdersID = 1,
                            Name = "Citronmaane",
                            Quantity = 232,
                            RecipeID = 1
                        },
                        new
                        {
                            BakingGoodsID = 2,
                            CompanyOrdersID = 2,
                            Name = "Baklava",
                            Quantity = 1000,
                            RecipeID = 2
                        },
                        new
                        {
                            BakingGoodsID = 3,
                            CompanyOrdersID = 3,
                            Name = "Jalabe",
                            Quantity = 423,
                            RecipeID = 3
                        },
                        new
                        {
                            BakingGoodsID = 4,
                            CompanyOrdersID = 4,
                            Name = "Kunefe",
                            Quantity = 999,
                            RecipeID = 4
                        });
                });

            modelBuilder.Entity("bad4.Models.Batch", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<int>("BakingGoodsID")
                        .HasColumnType("int");

                    b.Property<float>("Delay")
                        .HasColumnType("real");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchID");

                    b.HasIndex("BakingGoodsID");

                    b.ToTable("Batch");

                    b.HasData(
                        new
                        {
                            BatchID = 1,
                            BakingGoodsID = 1,
                            Delay = 40f,
                            FinishTime = new DateTime(2024, 5, 5, 23, 36, 33, 159, DateTimeKind.Local).AddTicks(3089),
                            StartTime = new DateTime(2024, 5, 5, 22, 56, 33, 159, DateTimeKind.Local).AddTicks(3030)
                        },
                        new
                        {
                            BatchID = 2,
                            BakingGoodsID = 2,
                            Delay = 0f,
                            FinishTime = new DateTime(2024, 5, 6, 0, 6, 33, 159, DateTimeKind.Local).AddTicks(3096),
                            StartTime = new DateTime(2024, 5, 5, 23, 46, 33, 159, DateTimeKind.Local).AddTicks(3095)
                        },
                        new
                        {
                            BatchID = 3,
                            BakingGoodsID = 3,
                            Delay = 20f,
                            FinishTime = new DateTime(2024, 5, 6, 0, 36, 33, 159, DateTimeKind.Local).AddTicks(3099),
                            StartTime = new DateTime(2024, 5, 6, 0, 6, 33, 159, DateTimeKind.Local).AddTicks(3098)
                        },
                        new
                        {
                            BatchID = 4,
                            BakingGoodsID = 4,
                            Delay = 56f,
                            FinishTime = new DateTime(2024, 5, 6, 1, 26, 33, 159, DateTimeKind.Local).AddTicks(3102),
                            StartTime = new DateTime(2024, 5, 6, 1, 6, 33, 159, DateTimeKind.Local).AddTicks(3101)
                        });
                });

            modelBuilder.Entity("bad4.Models.CompanyOrders", b =>
                {
                    b.Property<int>("CompanyOrdersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyOrdersID"));

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyOrdersID");

                    b.ToTable("CompanyOrders");

                    b.HasData(
                        new
                        {
                            CompanyOrdersID = 1,
                            DeliveryDate = "12032002 2205",
                            DeliveryPlace = "Superbrugsen"
                        },
                        new
                        {
                            CompanyOrdersID = 2,
                            DeliveryDate = "02052001 2240",
                            DeliveryPlace = "Bilka"
                        },
                        new
                        {
                            CompanyOrdersID = 3,
                            DeliveryDate = "16032003 1600",
                            DeliveryPlace = "Lidl"
                        },
                        new
                        {
                            CompanyOrdersID = 4,
                            DeliveryDate = "03082001 2359",
                            DeliveryPlace = "SuperBest"
                        });
                });

            modelBuilder.Entity("bad4.Models.Dispatch", b =>
                {
                    b.Property<int>("TrackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackID"));

                    b.Property<int>("CompanyOrdersID")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("TrackID");

                    b.HasIndex("CompanyOrdersID");

                    b.ToTable("Dispatch");

                    b.HasData(
                        new
                        {
                            TrackID = 1,
                            CompanyOrdersID = 1,
                            Latitude = 931f,
                            Longitude = 139f
                        },
                        new
                        {
                            TrackID = 2,
                            CompanyOrdersID = 2,
                            Latitude = 957f,
                            Longitude = 759f
                        },
                        new
                        {
                            TrackID = 3,
                            CompanyOrdersID = 3,
                            Latitude = 1f,
                            Longitude = 529f
                        },
                        new
                        {
                            TrackID = 4,
                            CompanyOrdersID = 4,
                            Latitude = 923f,
                            Longitude = 329f
                        });
                });

            modelBuilder.Entity("bad4.Models.Ingredients", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RecipeID", "StockID");

                    b.HasIndex("StockID");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            StockID = 1,
                            Quantity = 1000
                        },
                        new
                        {
                            RecipeID = 1,
                            StockID = 2,
                            Quantity = 2300
                        },
                        new
                        {
                            RecipeID = 1,
                            StockID = 3,
                            Quantity = 3000
                        },
                        new
                        {
                            RecipeID = 1,
                            StockID = 4,
                            Quantity = 1230
                        },
                        new
                        {
                            RecipeID = 2,
                            StockID = 3,
                            Quantity = 100
                        },
                        new
                        {
                            RecipeID = 2,
                            StockID = 4,
                            Quantity = 2400
                        },
                        new
                        {
                            RecipeID = 2,
                            StockID = 5,
                            Quantity = 250
                        },
                        new
                        {
                            RecipeID = 2,
                            StockID = 2,
                            Quantity = 300
                        },
                        new
                        {
                            RecipeID = 3,
                            StockID = 7,
                            Quantity = 1000
                        },
                        new
                        {
                            RecipeID = 3,
                            StockID = 2,
                            Quantity = 2300
                        },
                        new
                        {
                            RecipeID = 3,
                            StockID = 6,
                            Quantity = 230
                        },
                        new
                        {
                            RecipeID = 3,
                            StockID = 3,
                            Quantity = 15000
                        },
                        new
                        {
                            RecipeID = 4,
                            StockID = 7,
                            Quantity = 200
                        },
                        new
                        {
                            RecipeID = 4,
                            StockID = 8,
                            Quantity = 300
                        },
                        new
                        {
                            RecipeID = 4,
                            StockID = 3,
                            Quantity = 200
                        },
                        new
                        {
                            RecipeID = 4,
                            StockID = 4,
                            Quantity = 300
                        });
                });

            modelBuilder.Entity("bad4.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            Name = "Citronmaane"
                        },
                        new
                        {
                            RecipeID = 2,
                            Name = "Baklava"
                        },
                        new
                        {
                            RecipeID = 3,
                            Name = "Jalabe"
                        },
                        new
                        {
                            RecipeID = 4,
                            Name = "Kunefe"
                        });
                });

            modelBuilder.Entity("bad4.Models.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockID");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            StockID = 1,
                            Name = "Flour",
                            Quantity = 123
                        },
                        new
                        {
                            StockID = 2,
                            Name = "Leftover Cake",
                            Quantity = 435
                        },
                        new
                        {
                            StockID = 3,
                            Name = "Salt",
                            Quantity = 342
                        },
                        new
                        {
                            StockID = 4,
                            Name = "Milk",
                            Quantity = 546
                        },
                        new
                        {
                            StockID = 5,
                            Name = "Egg",
                            Quantity = 234
                        },
                        new
                        {
                            StockID = 6,
                            Name = "Yeast",
                            Quantity = 457
                        },
                        new
                        {
                            StockID = 7,
                            Name = "Rum",
                            Quantity = 234
                        },
                        new
                        {
                            StockID = 8,
                            Name = "Baking Powder",
                            Quantity = 675
                        },
                        new
                        {
                            StockID = 9,
                            Name = "Baking soda",
                            Quantity = 243
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("bad4.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("bad4.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bad4.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("bad4.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bad4.Models.Allergen", b =>
                {
                    b.HasOne("bad4.Models.Stock", "Stock")
                        .WithOne("Allergen")
                        .HasForeignKey("bad4.Models.Allergen", "StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("bad4.Models.BakingGoods", b =>
                {
                    b.HasOne("bad4.Models.CompanyOrders", "CompanyOrders")
                        .WithMany("BakingGoods")
                        .HasForeignKey("CompanyOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bad4.Models.Recipe", "Recipe")
                        .WithOne("BakingGoods")
                        .HasForeignKey("bad4.Models.BakingGoods", "RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOrders");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("bad4.Models.Batch", b =>
                {
                    b.HasOne("bad4.Models.BakingGoods", "BakingGoods")
                        .WithMany("Batch")
                        .HasForeignKey("BakingGoodsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BakingGoods");
                });

            modelBuilder.Entity("bad4.Models.Dispatch", b =>
                {
                    b.HasOne("bad4.Models.CompanyOrders", "CompanyOrders")
                        .WithMany("Dispatch")
                        .HasForeignKey("CompanyOrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOrders");
                });

            modelBuilder.Entity("bad4.Models.Ingredients", b =>
                {
                    b.HasOne("bad4.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bad4.Models.Stock", "Stock")
                        .WithMany("Ingredients")
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("bad4.Models.BakingGoods", b =>
                {
                    b.Navigation("Batch");
                });

            modelBuilder.Entity("bad4.Models.CompanyOrders", b =>
                {
                    b.Navigation("BakingGoods");

                    b.Navigation("Dispatch");
                });

            modelBuilder.Entity("bad4.Models.Recipe", b =>
                {
                    b.Navigation("BakingGoods");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("bad4.Models.Stock", b =>
                {
                    b.Navigation("Allergen");

                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
