version: '3.8'

services:
  api:
    container_name: aspnet-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - 6060:80
    depends_on:
      - api_db
      - log_db
    links:
      - api_db:mssql-server

  api_db:
    container_name: mssql-server
    image: rushaa25/bad4:sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: massakadiablo99
    ports:
      - 1433:1433

  log_db:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017

 